#!/bin/bash

# Validates whether commit message is of a certain format.
# Aborts commit if message is unsatisfactory

# Standard commit from Pivotal Tracker [#135316555:Feature]Create Kafka Audit Trail
commit_standard_regex='^[A-Za-z0-9]+-[0-9]+.+|merge'
error_message="Aborting commit. Please ensure your commit message meets the
               standard requirement. 'JIRA# Commit Message'
              Use 'CF2-234 Create Kafka Audit Trail' for reference"


if ! grep -iqE "$commit_standard_regex" "$1"; then
    echo "$error_message" >&2
    exit 1
fi